### PR TITLE
feat: Add OptimisticDeleteStream

### LINKED ISSUE #18: Fix PostgreSQL KeyStore to remove encryption keys upon delete
Delete currently only performs a soft delete:
`UPDATE vault SET DeletedAtTimestamp = $1 WHERE SubjectID = $2`

This should set `EncryptionKey` to empty string.

[Code](https://github.com/inklabs/rangedb/blob/836e24b45466b9d91da408ec3488501573228a32/pkg/crypto/provider/postgreskeystore/postgres_keystore.go#L89-L98)

### PR DESCRIPTION
**Pull request by pdt256**
WIP Support for deleting event streams

BREAKING CHANGE: Alters starting global/stream sequence number from 0 to 1
Closes #18

### CODE REVIEW

**Review by yordis — APPROVED** [review]
I like to pretend I am doing a good job code reviewing but holy shit this was a lot 😭 I lost track of most files

**Comment by yordis** [comment]
> BREAKING CHANGE: Alters starting global/stream sequence number from 0 to 1

I will suggest to bump the major version

**Comment by pdt256** [comment]
> I like to pretend I am doing a good job code reviewing but holy shit this was a lot 😭 I lost track of most files

I appreciate you taking the time to review.

Sorry, it quickly got large. I am happy to create separate PRs for each change if that helps.

**Comment by pdt256** [comment]
> > BREAKING CHANGE: Alters starting global/stream sequence number from 0 to 1
> 
> I will suggest to bump the major version

I will stay on pre-release version 0 until the store stabilizes. This PR will bump from `v0.11.0` to `v0.12.0`.

A `v1.0.0` will be coming sometime this year. Hopefully around Q3.

**Pull request merged**
