### PR TITLE
build: move from travis ci to github actions

### PR DESCRIPTION
**Pull request by mhatvan**
## Description

There are some code changes left where I don't know how it's supposed to be set up:

- GitHub action would run on pull request currently, is that how it is desired?
- From `travis` services configuration it is not clear which version of `postgresql` and which `docker` image is in use. Versions for `postgresql` as well as `docker` image still have to be configured and pinned down ideally
- No clue what `cc-test-reporter` is for, `before-build` and `after-build` hooks have to be updated to GitHub Actions
- I kept the `travis.yml` file for now, it has to be deleted after switch to GitHub actions is complete.

## Changes

- add `actions.yml` with the same functionality as `.travis.yml`

Closes https://github.com/inklabs/rangedb/issues/24

### CODE REVIEW

**Comment by pdt256** [comment]
First off, thank you so much @mhatvan!

> GitHub action would run on pull request currently, is that how it is desired?

Correct

> From travis services configuration it is not clear which version of postgresql and which docker image is in use. Versions for postgresql as well as docker image still have to be configured and pinned down ideally

Let's go with the current latest for each docker image.
- vault:1.9.1
- postgres:14.1

> No clue what cc-test-reporter is for, before-build and after-build hooks have to be updated to GitHub Actions

This is for [code coverage](https://codeclimate.com/github/inklabs/rangedb). I will setup the appropriate secrets.

> I kept the travis.yml file for now, it has to be deleted after switch to GitHub actions is complete.

This file can be deleted now.

**Comment by pdt256** [comment]
I just set the `secrets.CC_TEST_REPORTER_ID` secret on this repository. You may need to expose the `CC_TEST_REPORTER_ID` environment variable.

```yml
env:
   CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
```

This Action may help: https://github.com/paambaati/codeclimate-action

**Comment by pdt256** [comment]
Secrets have been set for docker. The following Action can be used instead of `echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin`

https://github.com/marketplace/actions/docker-login#docker-hub

```yml
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```

**Comment by mhatvan** [comment]
I pushed another commit that:

- replaced custom code with `docker/login-action`
- set up `hashicorp/vault-action` (instead of `vault:1.9.1`)
- deleted now redundant `.travis.yml`
- configured `paambaati/codeclimate-action`, but unsure at which step it's supposed to run exactly

I would recommend taking over the PR, as I have no insights into the current Travis CI pipeline, which leads to me only guessing the correct steps for GH actions ;)

**Review by pdt256 — APPROVED** [review]

**Pull request merged**
